# rpc
rpc:
  port: ":8535"

# 日志配置
logger_jsonFile: "config/log.json"

mysql:
  #打开数据库的最大连接数
  max_open_conn: 150
  #连接池中的保持连接的最大连接数
  max_idle_conn: 100
  #连接复用时间 1min=60000000000 10mins
  conn_max_life_time: 600000000000
  #链接
  source_name: root:mysql2022@tcp(13.213.61.14:13306)/cmp_chain?parseTime=true&charset=utf8&loc=Local

